language: bash

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y install qemu-static binfmt

deploy:
  provider: script
  script: 
    bash ./build-docker.sh x86
    bash ./build-docker.sh armhf
    bash ./build-docker.sh arm64
  on:
    branch: master
