# https://www.docker.com/blog/docker-v2-github-action-is-now-ga/
# https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/
# https://docs.github.com/en/actions/guides/publishing-docker-images

name: CD - Build and push multi-arch images

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            ghcr.io/${{ github.repository }}

      - name: Set the platforms
        run: |
          echo "platforms=armhf x86 arm64" >> $GITHUB_ENV

      - name: Build containers
        run: |
             for arch in ${{ env.platforms }}
             do
              ./build-docker.sh $arch
             done

      - name: Push containers to github container registry as tag
        if: contains(github.ref, 'refs/tags/')
        run: |
             version=$(git describe --tags --always)
             version=${version%-*-*}
             for arch in ${{ env.platforms }}
             do
                docker tag ownyourbits/nextcloudpi-$arch:latest ghcr.io/${{ github.repository_owner }}/nextcloudpi-$arch:${version}
                docker push ghcr.io/${{ github.repository_owner }}/nextcloudpi-$arch:${version}
              done

      - name: Push containers to github container registry as latest
        if: contains(github.ref, 'refs/heads/')
        run: |
             for arch in ${{ env.platforms }}
             do
                docker tag ownyourbits/nextcloudpi-$arch:latest ghcr.io/${{ github.repository_owner }}/nextcloudpi-$arch:latest
                docker push ghcr.io/${{ github.repository_owner }}/nextcloudpi-$arch:latest
             done
